server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://114.215.183.131:3306/spring_boot_case?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: jseoss2016!
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
    prefix: classpath:templates
    suffix: .html
    mode: HTML
    encoding: utf-8
  resources:
    static-locations: classpath:static
mybatis:
  type-aliases-package: com.wjl.loans.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback.xml
servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB
